using UnityEngine;
using UnityEngine.Rendering;

/// <summary>
/// Tiny missile ammo display that floats above a player aircraft. Builds one
/// dot per <see cref="AircraftWeapon.maxAmmo"/> at runtime, then polls the
/// weapon's <see cref="AircraftWeapon.CurrentAmmo"/> every LateUpdate and
/// re-colours each dot (filled vs empty).
///
/// Hierarchy expected:
///   AircraftRoot                (has Health, AirUnitController, AircraftWeapon)
///     └── AmmoIndicator         (this component + autogenerated Dot_N children)
///           ├── Dot_0
///           └── Dot_1           (more dots if maxAmmo > 2)
///
/// Setup:
///   1. Attach to a CHILD GameObject of the aircraft. The parent must have
///      AirUnitController, AircraftWeapon, and Health components.
///   2. The dots are built procedurally — no Inspector references required.
///   3. Hidden automatically when Health.team is not Player, so future enemy
///      aircraft don't leak ammo info to the player.
///   4. Use Tools → RTS → Air System → Repair Strike Jet Ammo Indicator to
///      add this child to existing StrikeJetPrefab.prefab.
///
/// What it does NOT do:
///   - Add a Collider (dots are stripped of their auto-colliders).
///   - Affect selection (layer is IgnoreRaycast).
///   - Touch the NavMesh.
///   - Mutate aircraft state — it only reads CurrentAmmo / maxAmmo from
///     the AircraftWeapon on the parent.
/// </summary>
[DisallowMultipleComponent]
public class AircraftAmmoIndicator : MonoBehaviour
{
    private const int IgnoreRaycastLayer = 2;

    // ------------------------------------------------------------------ //
    // Inspector
    // ------------------------------------------------------------------ //

    [Header("Layout")]
    [Tooltip("Vertical offset above the aircraft pivot, in world units.")]
    public float heightOffset = 2.5f;

    [Tooltip("Diameter of each dot, in world units.")]
    public float dotSize = 0.30f;

    [Tooltip("Horizontal centre-to-centre distance between adjacent dots, in world units.")]
    public float dotSpacing = 0.45f;

    [Header("Colours")]
    [Tooltip("Colour for a loaded missile.")]
    [ColorUsage(false)] public Color filledColor = new Color(0.20f, 0.85f, 1.00f);

    [Tooltip("Colour for a spent missile slot.")]
    [ColorUsage(false)] public Color emptyColor  = new Color(0.20f, 0.20f, 0.22f);

    // ------------------------------------------------------------------ //
    // Runtime state
    // ------------------------------------------------------------------ //

    private Transform         ownerTransform;
    private AircraftWeapon    weapon;
    private Camera            cam;
    private GameObject[]      dots;
    private Material          filledMat;
    private Material          emptyMat;
    private int               lastObservedAmmo = -1;

    // ------------------------------------------------------------------ //
    // Unity lifecycle
    // ------------------------------------------------------------------ //

    private void Awake()
    {
        Transform owner = transform.parent;
        if (owner == null)
        {
            Debug.LogWarning($"AircraftAmmoIndicator on '{name}': no parent. Disabling.");
            enabled = false;
            return;
        }

        // The brain isn't strictly required for the indicator, but its presence
        // identifies the parent as an aircraft. The weapon is the actual data source.
        AirUnitController controller = owner.GetComponent<AirUnitController>();
        weapon = owner.GetComponent<AircraftWeapon>();

        if (controller == null || weapon == null)
        {
            Debug.LogWarning($"AircraftAmmoIndicator on '{name}': parent '{owner.name}' is " +
                             $"missing AirUnitController or AircraftWeapon. Disabling.");
            enabled = false;
            return;
        }

        // Hide for non-player aircraft so enemy ammo isn't leaked through the HUD.
        Health h = owner.GetComponent<Health>();
        if (h == null || h.team != Health.Team.Player)
        {
            gameObject.SetActive(false);
            return;
        }

        ownerTransform = owner;
        cam = Camera.main;
        EnsureMaterials();
        BuildDots(weapon.maxAmmo);
    }

    private void LateUpdate()
    {
        if (weapon == null || ownerTransform == null) return;

        // Follow the parent, billboard to the camera.
        transform.position = ownerTransform.position + Vector3.up * heightOffset;

        if (cam == null)
        {
            cam = Camera.main;
            if (cam == null) return;
        }
        transform.rotation = cam.transform.rotation;

        // Refresh colours only on actual change — cheap.
        int ammo = weapon.CurrentAmmo;
        if (ammo != lastObservedAmmo)
        {
            Refresh(ammo);
            lastObservedAmmo = ammo;
        }
    }

    // ------------------------------------------------------------------ //
    // Visual construction
    // ------------------------------------------------------------------ //

    /// <summary>Builds N dot primitives evenly spaced around local X = 0.</summary>
    private void BuildDots(int count)
    {
        // Clear any pre-existing children (e.g. if the editor tool seeded them
        // and we want a clean rebuild on Awake).
        for (int i = transform.childCount - 1; i >= 0; i--)
            Destroy(transform.GetChild(i).gameObject);

        dots = new GameObject[count];
        for (int i = 0; i < count; i++)
        {
            GameObject d = GameObject.CreatePrimitive(PrimitiveType.Sphere);
            d.name = $"Dot_{i}";
            d.transform.SetParent(transform, worldPositionStays: false);
            d.transform.localScale    = Vector3.one * dotSize;
            d.transform.localPosition = new Vector3(
                (i - (count - 1) * 0.5f) * dotSpacing, 0f, 0f);
            d.transform.localRotation = Quaternion.identity;

            // Strip auto-collider so dots don't intercept clicks.
            Collider c = d.GetComponent<Collider>();
            if (c != null) Destroy(c);

            // Renderer cosmetics — start filled; LateUpdate's first poll
            // overrides immediately based on actual ammo.
            Renderer r = d.GetComponent<Renderer>();
            if (r != null)
            {
                r.sharedMaterial    = filledMat;
                r.shadowCastingMode = ShadowCastingMode.Off;
                r.receiveShadows    = false;
            }

            d.layer = IgnoreRaycastLayer;
            dots[i] = d;
        }
    }

    private void Refresh(int ammo)
    {
        if (dots == null) return;
        for (int i = 0; i < dots.Length; i++)
        {
            if (dots[i] == null) continue;
            Renderer r = dots[i].GetComponent<Renderer>();
            if (r == null) continue;
            r.sharedMaterial = (i < ammo) ? filledMat : emptyMat;
        }
    }

    private void EnsureMaterials()
    {
        Shader shader = ResolveLitShader();

        if (filledMat == null)
        {
            filledMat = new Material(shader) { name = "AmmoDot_Filled", color = filledColor };
            if (filledMat.HasProperty("_BaseColor"))
                filledMat.SetColor("_BaseColor", filledColor);
            if (filledMat.HasProperty("_EmissionColor"))
            {
                filledMat.EnableKeyword("_EMISSION");
                filledMat.SetColor("_EmissionColor", filledColor * 0.9f);
            }
        }

        if (emptyMat == null)
        {
            emptyMat = new Material(shader) { name = "AmmoDot_Empty", color = emptyColor };
            if (emptyMat.HasProperty("_BaseColor"))
                emptyMat.SetColor("_BaseColor", emptyColor);
        }
    }

    private static Shader ResolveLitShader()
    {
        RenderPipelineAsset rp = GraphicsSettings.defaultRenderPipeline;
        bool isURP = rp != null && rp.GetType().Name.Contains("Universal");

        Shader urp = Shader.Find("Universal Render Pipeline/Lit");
        Shader std = Shader.Find("Standard");

        if (isURP && urp != null) return urp;
        if (!isURP && std != null) return std;
        return urp ?? std ?? Shader.Find("Hidden/InternalErrorShader");
    }
}
