using UnityEngine;
using UnityEngine.Rendering;

/// <summary>
/// Floating mini health bar that hovers above a unit. Subscribes to the unit's
/// Health.OnHealthChanged event so it only does work on actual damage, and
/// billboards itself to face Camera.main every LateUpdate so it stays readable
/// from the tilted RTS camera.
///
/// Hierarchy expected:
///   UnitRoot                  (has Health)
///     └── HealthBar           (this script + autogenerated children below)
///           ├── Background    (dark cube, full bar width)
///           └── Fill          (coloured cube, scaled from the LEFT edge)
///
/// Setup:
///   1. Add this component to a CHILD GameObject of your unit (the parent
///      must have a Health component — Health is found via transform.parent).
///   2. No Inspector references are required. If "Background"/"Fill" children
///      are missing they are built procedurally in Awake using cube primitives.
///   3. Run Tools → RTS → Add Health Bars To Units to wire everything for
///      SoldierPrefab and the current scene in one click.
///
/// What it deliberately does NOT do:
///   • Add a Collider — colliders on the cubes are stripped at runtime so
///     the bar never intercepts selection or attack raycasts.
///   • Add SelectableUnit — the bar is not selectable.
///   • Touch the NavMesh — no NavMeshAgent / NavMeshObstacle.
///   • Modify Health, UnitCombat, or any other component on the unit.
///
/// When the parent unit is destroyed, this child goes with it automatically.
/// </summary>
[DisallowMultipleComponent]
public class HealthBar : MonoBehaviour
{
    // Unity's built-in IgnoreRaycast layer index — defence in depth even
    // though the cubes' colliders are also destroyed.
    private const int IgnoreRaycastLayer = 2;

    // ------------------------------------------------------------------ //
    // Inspector
    // ------------------------------------------------------------------ //

    [Header("Layout")]
    [Tooltip("Vertical offset above the parent's pivot, in world units")]
    public float heightOffset = 1.8f;

    [Tooltip("Width (X) and height (Y) of the background bar, in world units")]
    public Vector2 size = new Vector2(1.0f, 0.12f);

    [Tooltip("Background depth (Z thickness). Fill is rendered slightly thicker to avoid Z-fighting.")]
    public float depth = 0.04f;

    [Header("Colours")]
    [ColorUsage(false)] public Color backgroundColor = new Color(0.07f, 0.07f, 0.07f);
    [ColorUsage(false)] public Color highColor       = new Color(0.22f, 0.82f, 0.22f);   // green
    [ColorUsage(false)] public Color midColor        = new Color(0.93f, 0.85f, 0.10f);   // yellow
    [ColorUsage(false)] public Color lowColor        = new Color(0.88f, 0.18f, 0.18f);   // red

    [Header("Colour Thresholds")]
    [Tooltip("Fill ratio at or above this is shown in highColor (default 0.75 → green when ≥75%)")]
    [Range(0f, 1f)] public float highThreshold = 0.75f;

    [Tooltip("Fill ratio at or above this (but below high) is shown in midColor " +
             "(default 0.35 → yellow between 35% and 75%, red below 35%)")]
    [Range(0f, 1f)] public float midThreshold  = 0.35f;

    [Header("Behaviour")]
    [Tooltip("If true, the bar is hidden while health is at maximum.")]
    public bool hideWhenFull = false;

    // ------------------------------------------------------------------ //
    // Runtime state
    // ------------------------------------------------------------------ //

    private Transform owner;          // unit root (parent)
    private Health health;
    private Camera cam;

    private Transform backgroundGO;
    private Transform fillGO;
    private Material  fillMaterial;
    private Material  backgroundMaterial;

    // ------------------------------------------------------------------ //
    // Unity lifecycle
    // ------------------------------------------------------------------ //

    private void Awake()
    {
        owner  = transform.parent;
        health = owner != null ? owner.GetComponent<Health>() : null;
        cam    = Camera.main;

        EnsureBarVisuals();

        if (health == null)
        {
            Debug.LogWarning($"HealthBar on '{name}': no Health component on parent '{owner?.name}'. " +
                             "Disabling — attach HealthBar as a child of a Health-bearing unit.");
            enabled = false;
            return;
        }

        health.OnHealthChanged += OnHealthChanged;
    }

    private void Start()
    {
        // Start runs AFTER every Awake, so Health.CurrentHealth is fully
        // initialised by now. Doing the initial paint here avoids a one-frame
        // glitch where the bar appears at 0% before Health's own Awake ran.
        if (health != null)
            RefreshFill(health.CurrentHealth, health.maxHealth);
    }

    private void OnDestroy()
    {
        // Unity's overloaded == catches destroyed-object references and skips.
        if (health != null)
            health.OnHealthChanged -= OnHealthChanged;
    }

    private void LateUpdate()
    {
        if (owner == null) return;

        // Re-cache Camera.main lazily — covers scene loads where main camera
        // is created after this component's Awake.
        if (cam == null)
        {
            cam = Camera.main;
            if (cam == null) return;
        }

        transform.position = owner.position + Vector3.up * heightOffset;
        // Billboard: copy the camera's rotation so the bar plane stays
        // parallel to the camera plane (readable from the tilted RTS view).
        transform.rotation = cam.transform.rotation;
    }

    // ------------------------------------------------------------------ //
    // Health event handler
    // ------------------------------------------------------------------ //

    private void OnHealthChanged(float current, float max) => RefreshFill(current, max);

    private void RefreshFill(float current, float max)
    {
        float pct = max > 0f ? Mathf.Clamp01(current / max) : 0f;

        // Left-anchor trick: the Fill cube's pivot is centred, so to keep its
        // LEFT edge at the bar's left edge we have to shift the centre by
        // (pct - 1) * width / 2 while scaling its width by pct.
        fillGO.localScale = new Vector3(
            size.x * pct,
            size.y * 0.85f,
            depth * 1.5f);
        fillGO.localPosition = new Vector3(
            size.x * (pct - 1f) * 0.5f,
            0f,
            0f);

        Color c = pct >= highThreshold ? highColor
                : pct >= midThreshold  ? midColor
                                       : lowColor;

        fillMaterial.color = c;
        if (fillMaterial.HasProperty("_BaseColor"))
            fillMaterial.SetColor("_BaseColor", c);

        bool show = !(hideWhenFull && pct >= 1f);
        if (backgroundGO.gameObject.activeSelf != show)
            backgroundGO.gameObject.SetActive(show);
        if (fillGO.gameObject.activeSelf != show)
            fillGO.gameObject.SetActive(show);
    }

    // ------------------------------------------------------------------ //
    // Visual construction — idempotent, builds children if missing
    // ------------------------------------------------------------------ //

    /// <summary>
    /// Guarantees Background + Fill children exist, have the right scale, no
    /// colliders, and live on the IgnoreRaycast layer. Idempotent — safe to
    /// call when the editor tool has already pre-built them.
    /// </summary>
    private void EnsureBarVisuals()
    {
        Transform bg = transform.Find("Background");
        if (bg == null)
            bg = BuildPrimitiveChild("Background", new Vector3(size.x, size.y, depth), backgroundColor);
        else
            ConfigureExistingChild(bg, new Vector3(size.x, size.y, depth), backgroundColor);
        backgroundGO = bg;

        Transform fill = transform.Find("Fill");
        if (fill == null)
            fill = BuildPrimitiveChild("Fill", new Vector3(size.x, size.y * 0.85f, depth * 1.5f), highColor);
        else
            ConfigureExistingChild(fill, new Vector3(size.x, size.y * 0.85f, depth * 1.5f), highColor);
        fillGO = fill;

        backgroundMaterial = backgroundGO.GetComponent<Renderer>()?.material;
        fillMaterial       = fillGO.GetComponent<Renderer>()?.material;

        SetLayerRecursive(transform, IgnoreRaycastLayer);
    }

    private Transform BuildPrimitiveChild(string name, Vector3 scale, Color color)
    {
        GameObject go = GameObject.CreatePrimitive(PrimitiveType.Cube);
        go.name = name;
        go.transform.SetParent(transform, worldPositionStays: false);
        go.transform.localPosition = Vector3.zero;
        go.transform.localRotation = Quaternion.identity;
        go.transform.localScale    = scale;

        ConfigureRenderer(go, color);

        Collider col = go.GetComponent<Collider>();
        if (col != null) Destroy(col);

        return go.transform;
    }

    private void ConfigureExistingChild(Transform t, Vector3 scale, Color color)
    {
        t.localPosition = Vector3.zero;
        t.localRotation = Quaternion.identity;
        t.localScale    = scale;
        ConfigureRenderer(t.gameObject, color);

        Collider col = t.GetComponent<Collider>();
        if (col != null) Destroy(col);
    }

    private static void ConfigureRenderer(GameObject go, Color color)
    {
        Renderer r = go.GetComponent<Renderer>();
        if (r == null) return;

        Material m = new Material(ResolveLitShader()) { color = color };
        if (m.HasProperty("_BaseColor"))
            m.SetColor("_BaseColor", color);

        r.sharedMaterial      = m;
        r.shadowCastingMode   = ShadowCastingMode.Off;
        r.receiveShadows      = false;
    }

    private static void SetLayerRecursive(Transform t, int layer)
    {
        t.gameObject.layer = layer;
        for (int i = 0; i < t.childCount; i++)
            SetLayerRecursive(t.GetChild(i), layer);
    }

    private static Shader ResolveLitShader()
    {
        RenderPipelineAsset rp = GraphicsSettings.defaultRenderPipeline;
        bool isURP = rp != null && rp.GetType().Name.Contains("Universal");

        Shader urp = Shader.Find("Universal Render Pipeline/Lit");
        Shader std = Shader.Find("Standard");

        if (isURP && urp != null) return urp;
        if (!isURP && std != null) return std;
        return urp ?? std ?? Shader.Find("Hidden/InternalErrorShader");
    }
}
